server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/users/**
        - id: productservice
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/api/products/**
        - id: orderservice
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
``
