spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AuthServiceDatabase
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      
app:
  jwt:
    secret: bXlTdXBlclNlY3JldEtleUZvckpXVFRoYXRJc0F0TGVhc3QyNTZCaXRzTG9uZzEyMzQ1
