spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AuthServiceDatabase
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      
app:
  jwt:
    secret: bXlTdXBlclNlY3JldEtleUZvckpXVFRoYXRJc0F0TGVhc3QyNTZCaXRzTG9uZzEyMzQ1

# Rate Limiter configuration
resilience4j:
  ratelimiter:
    instances:
      AuthServiceRateLimiter:
        limit-for-period: 5      # permits per cycle
        limit-refresh-period: 2s   # cycle length
        timeout-duration: 0        # 0 = reject immediately, don't queue
