spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserServiceDatabase
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  jackson:
    mapper:
      sort-properties-alphabetically: false
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    userproducer:
      topic: user-service-topic
