spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserServiceDatabase
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  jackson:
    mapper:
      sort-properties-alphabetically: false
  kafka:
   producer:
     bootstrap-servers: localhost:9092
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
     properties:
      spring:
        json:
          type:
            mapping: "user:com.cognizant.userservice.dtos.UserDTO"

# Rate Limiter configuration
resilience4j:
  ratelimiter:
    instances:
      UserServiceRateLimiter:
        limit-for-period: 5      # permits per cycle
        limit-refresh-period: 2s   # cycle length
        timeout-duration: 0        # 0 = reject immediately, don't queue
